[package]
name = "cw-paginate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { version = "1.0.0" }
cosmwasm-storage = { version = "1.0.0" }
cw-storage-plus = "0.13"
serde = { version = "1.0", default-features = false }

[dev-dependencies]
cw-multi-test = "0.13"
